- .gitignore
- examples/simpleexample.py
- postpic/__init__.py
- postpic/analyzer/__init__.py
- postpic/datareader/__init__.py
Improvements on usability
Most importantly:
1) Dumpreader_ifc inherits all the high level Functions from the FieldAnalyzer. So there is no need to call the FieldAnalyzer directly anymore
2) ParticleAnalyzer and chooseCode got linked directly into postpic, no need to call the subpackages anymore.
> usability improvements

- .gitignore
- .travis.yml
- examples/particleshapedemo.py
- examples/simpleexample.py
- examples/time_cythonfunctions.py
- postpic/analyzer/particles.py
- postpic/cythonfunctions.pyx
- postpic/datahandling.py
- postpic/datareader/dummy.py
- run-tests.py
- setup.py
- test/test_cythonfunctions.py
these histogram functions are much faster than the numpy histograms and they also offer the possibility to make use of higher order particle shapes to transfer particle properties to grid properly. Cython is needed.
> added own histogram function

- postpic/_field_calc.py
- postpic/datareader/__init__.py
- postpic/datareader/datareader.py
- postpic/datareader/dummy.py
- postpic/datareader/epochsdf.py
- postpic/particles.py
Every dataset is now allowed to have its own grid.
Epoch and dummy reader are updated to support the change
> add mutiple grid support

- .gitignore
- .travis.yml
- examples/openPMD.py
- postpic/datareader/__init__.py
- postpic/datareader/openPMDh5.py
- postpic/particles.py
- run-tests.py
- setup.py
This PR adds a reader for OpenPMD conform hdf5 files.
> add OpenPMD h5 reader

- postpic/datareader/epochsdf.py
- postpic/particles.py
> fixes and improvements

- .travis.yml
> Travispython3.6

- postpic/datareader/epochsdf.py
Fix a bug in Sdfreader.gridspacing
> epochsdf.py: fix bug in calculation of gridspacing

- test/test_datahandling.py
add some additional tests for FFT
> fft: additional tests

- postpic/datahandling.py
> Field: make Field.matrix a property

- postpic/datahandling.py
- postpic/plotting/plotter_matplotlib.py
- test/test_datahandling.py
Field object has now new:
* real, imag and angle properties
* pad method
Also: plotter squeezes automatically
> Field: New properties and a method

- postpic/datahandling.py
- postpic/helper.py
- postpic/plotting/plotter_matplotlib.py
- test/test_datahandling.py
- test/test_helper.py
This pull request contains a new function kspace_propagate, which will evolve complex fields in time.
Other additions for Field:
* meshgrid method
> Add function kspace_propagate

- postpic/_field_calc.py
- postpic/datahandling.py
- postpic/datareader/datareader.py
- postpic/datareader/epochsdf.py
- postpic/helper.py
- postpic/plotting/plotter_matplotlib.py
- test/test_datahandling.py
- test/test_helper.py
Field:
* new method transform() for arbitrary coordinate transforms
* reimplemented topolar() to use transform()
* some fixes in squeeze() and mean()
Axis:
* new method value_to_index
helper:
* new functions polar2linear and linear2polar
> Field: New method transform

- .travis.yml
- postpic/datahandling.py
- postpic/helper.py
- setup.py
- test/test_datahandling.py
Field:
* FFT: use pyfftw if available
* FFT: added exponential_sign kwarg
* Use numexpr for kspace_propagate and _apply_linear_phase
* shift_grid_by refactored
* new integrate method
* improvements of handling the ._matrix
> Misc. improvements

- postpic/_postpic_version.py
> bump to 0.3

- postpic/plotting/plotter_matplotlib.py
> plotter: pass on remaining addField2d kwargs to imshow/pcolormesh

- CHANGELOG.md
- postpic/datahandling.py
- postpic/helper.py
- test/test_datahandling.py
map_coordinates now preserves the integral by applying the jacobian of
the transformation
> Field: transform renamed to map_coordinates

- postpic/helper.py
> restructured identifyspecies

- CHANGELOG.md
- postpic/_field_calc.py
- postpic/datahandling.py
- postpic/helper.py
- test/test_datahandling.py
- test/test_helper.py
k-space reconstruction from EPOCH dumps has greatly improved accuracy due to a new algorithm correctly incorporating the frequency response of the implicit linear interpolation performed by EPOCH's half-steps
> new kspace method

- .travis.yml
- postpic/datareader/epochsdf.py
Travis CI occasionally failes due to a bug in numpy and  matplotlib 2.1. See for example this:
https://travis-ci.org/skuschel/postpic/jobs/301484485
This shows up in Python 3.6 as well, however restarting the CI job sometimes fixes the problem. This PR attempts to fix the issue.
> Attempting to fix travis ci error

- postpic/experimental.py
Fix missing import in pp.experimental
> Fix missing import in pp.experimental

- postpic/_compat.py
- postpic/datahandling.py
- postpic/helper.py
moved compatibility functions from `helper` to new `module _compat`
> refactored compatibility stuff

- CHANGELOG.md
- postpic/datahandling.py
- test/test_datahandling.py
> Fix broadcasting

- postpic/datahandling.py
> Restore old extent behaviour

- postpic/datahandling.py
- postpic/io.py
- test/test_datahandling.py
- test/test_io.py
new functions to export scalar and vector fields to a VTK file suitable for viewing in paraview.
fixes #114
Rebased and rewritten version of #147
> Vtkexport for paraview

- postpic/datahandling.py
- postpic/io.py
- setup.py
- test/test_datahandling.py
> add Axis equality tests

- postpic/datahandling.py
- postpic/helper.py
- test/test_datahandling.py
Also don't need to copy them any longer when copying a Field
> Make Axis objects really immutable

- examples/particleshapedemo.py
- examples/time_cythonfunctions.py
- postpic/particles/_particlestogrid.pyx
- postpic/particles/_routines.py
- test/test_particlestogrid.py
adding spline3 shape for particle shapes.
closes #13
> add Spline3 particle shapes

- postpic/io/npy.py
> Fix: convert numpy arrays to lists on import

- CHANGELOG.md
- postpic/datahandling.py
- postpic/helper.py
- postpic/plotting/plotter_matplotlib.py
- test/test_datahandling.py
* plotter_matplotlib: allow imshow's option 'aspect' to be changed in addField2d
* plotter_matplotlib: new symmetric colormap
* Field: new method `Field.derivative` and tests
> Some new features

- postpic/datahandling.py
- postpic/helper.py
This just adds a monotonicity check to the Axis object
> Axis: Added monotonicity check

- postpic/io/image.py
> io.image: small fix for _readpng

- postpic/datahandling.py
Added `compressed` option to `Field.saveto`. Also improved Docstring.
> Field: Improved saveto method

- postpic/datahandling.py
> Field: add order argument to Field.copy

- CHANGELOG.md
- postpic/datahandling.py
- postpic/helper.py
- test/test_datahandling.py
- test/test_helper.py
Replaced scipy's implementation of `scipy.ndimage.map_coordinates` by a parallelized one
> Field.map_coordinates parallelized

- .travis.yml
- pip-requirements.txt
> CI: Fix for Ubuntu 1404

- postpic/datahandling.py
- postpic/helper.py
This should fix issue #222
Minimal change, should not affect anything else.
> Changed return type of `Field._normalize_slices`

- postpic/_compat/functions.py
- postpic/datahandling.py
- postpic/datareader/datareader.py
- postpic/particles/_routines.py
- postpic/particles/scalarproperties.py
> Pull abc's from collections.abc instead collections

- postpic/io/vtk.py
- postpic/particles/particles.py
> Fix calls to numpy.?stack methods

- postpic/datahandling.py
- postpic/helper.py
This fixes issue #231.
@skuschel this is a small, but critical fix. If you are ok with it, please just merge it.
> Fix issue #231

- postpic/datahandling.py
- test/test_datahandling.py
Better error msg for #233  and some test added.
fix #233
> better error msg if gridspacing is zero

- examples/kspace-test-2d.py
- run-tests.py
Added a script producing these plots:
[gaussian-env-arg.pdf](https://github.com/skuschel/postpic/files/3566157/gaussian-env-arg.pdf)
[gaussian-kspace.pdf](https://github.com/skuschel/postpic/files/3566158/gaussian-kspace.pdf)
example works with or without sdf. resource files are downloaded from my personal web server and hash-checked before being unpacked.
> added a kspace example script

- postpic/io/image.py
This should fix #241.
Tested on a 12-bit labview png image with imageio present and not present.
> Updated image reader logic to fix #241

- CHANGELOG.md
- postpic/_field_calc.py
- postpic/datahandling.py
- postpic/datareader/__init__.py
- postpic/datareader/datareader.py
- postpic/datareader/openPMDh5.py
- postpic/helper.py
- postpic/particles/particles.py
I have been writing a reader for the fbpic code ( https://github.com/fbpic/ )  over the last two month and I blieve that most of it is working now. There are still some convenience functions missing, that I can think of (like `Ex` and `Ey` instead instead of being forced to use `Er`, `Etheta`). But the internal mode expansion and understanding the format seem to work.
> add Fbpic reader

- .github/workflows/pythonpackage.yml
- .github/workflows/run-tests.yml
- .travis.yml
- run-tests.py
run test in github-actions. Also allow python2 test to fail due to end of its support.
> GitHub actions

- README.md
- update-gh-pages-branch.sh
* replace Travis badge by github action badge
* add script to create/update gh-pages branch
> Host Documentation on github pages

- .github/workflows/run-tests.yml
- .gitignore
- postpic/plotting/plotter_matplotlib.py
> update .gitignore and tests, matplotlib workaround

- CHANGELOG.md
Last version to support python2.
> version bump to v0.5

- postpic/datareader/__init__.py
- postpic/datareader/openPMDh5.py
- postpic/datareader/smileih5.py
> small fixes

- CHANGELOG.md
- postpic/particles/particles.py
- postpic/plotting/plotter_matplotlib.py
Added a new function to export Particle Tracks to hdf5. Also fixed a small bug for empty arrays in the plotter and updated a depracted function np.int.
> New function: exportToHdf5 for Particle Tracks
