skuschel/postpic

- setup.py
h5py became an optional dependency
sdf was added as optional dependency
h5py cant be installed on readthedocs server, so it needed to be removed from the required dependecies.
> make read-the-docs work again

- postpic/datareader/epochsdf.py
allows to read mass and charge of particles. This is particularly useful
since EPOCH can dump this as per species scalar value (introduced in EPOCH 4.7.0).
fixes #41
> read mass and charge from EPOCH dump

- postpic/datareader/openPMDh5.py
For scalar openPMD `records` such as a temperature field, a particle charge attribute, etc. the `record` itself is identical to its `record component`.
This commit fixes the detection of `record` attributes specific to fields (meshes) by checking either on the `record component` (scalar records) and if the attribute is not found there at the `parent` group (for vector records) level.
> openPMD: Fix Reader of Scalar Records

- examples/openPMD.py
Adds some minor additions to the examples:
- openPMD: spelling always with a lower "o"
- plotting of derived fields
- creation of a charge density field from a particle species
> openPMD: Example Additions

- postpic/datahandling.py
- postpic/helper.py
- test/test_datahandling.py
* Field: Fix `fft` for numpy < 1.10
* Fix use of np.meshgrid for numpy < 1.9
* Field: Fixed autocutout for scipy < 0.16
* Fixed use of np.broadcast_to for numpy<1.10
* Fix np.moveaxis for np<1.10
> Multiple Fixes for old Numpy/Scipy

- postpic/datareader/epochsdf.py
This also fixes a 'Exception ignored in: <bound method Sdfreader.__del__ >' when self._data = sdf.read(sdffile, dict=True) fails with a OSError'
> No need to override __del__ if you don't do anything special

- postpic/datahandling.py
- test/test_datahandling.py
- test/test_dumpreader.py
- test/test_field_calc.py
- test/test_helper.py
- test/test_particles.py
- test/test_particlestogrid.py
* Tests are added for the specific cases. 
* The Field will now raise an `IndexError` if an index is outside the physical extent (using physical indexing). Before this commit it was always using the nearest grid point, even if that is clearly far away.
> bugfix `Field.sqeeze` for shapes containing 0 length

- .travis.yml
tranvis suddenly yields an error on this command. Changing to libgfortran<1 magically helps. However, the may be the option to change to `libgfortran-ng` instead....
> travis: change libgfortran==1

- CHANGELOG.md
- postpic/datahandling.py
- postpic/io/__init__.py
- postpic/io/csv.py
- postpic/io/image.py
- postpic/plotting/plotter_matplotlib.py
- setup.py
Changed the io methods to have the following meaning:
* `postpic.Field` has methods `.loadfrom` and `.saveto`. These can be used to save a Field to a ` .npz` file for later use. Use `.loadfrom` to load a Field object from such a file. All attributes of the Field are restored.
* `postpic.Field` has methods `.export` and `.import`. These are used to export fields to and import fields from foreign file formats such as `.csv`, `.vtk`, `.png`, `.tif`, `.jpg`. It is not guaranteed to get all attributes back after `.export`ing and than `.import`ing a Field. Some formats are not available for both methods.
> WIP: Field: added method to load image files

- postpic/datahandling.py
this avoids a situation, where the user has a direct reference to a Fields axes list.
> Field._map_coordinates: make shallow copy of newaxes list

- CHANGELOG.md
- postpic/datahandling.py
- postpic/datareader/__init__.py
- postpic/helper.py
- test/test_datahandling.py
This PR finally adds reversed axis together with the `rot90` and `flip` functions including tests.
For most of the functions the behaviour with reversed axis is still not tested (like for `fft`). That would have to be done in another PR. 
Fix #174
> allow reversed axis

- postpic/datahandling.py
- test/test_datahandling.py
2 Test cases were not updated when we changed to immutable `Field`s. Also `Field._conjugate_grid` had a bug when a `0.0` was in `transformed_axes_origins`, because `bool(0.0) is False`  ...
> Some fixes for FFT

- postpic/datahandling.py
- test/test_datahandling.py
This changes the defaults for `Axis.grid` and `Axis.grid_node`. Before, the defaults were created using linear interpolation of whatever was explicitly given. Now, spline interpolation is used. This should make grid/grid_node more "compatible" with each other in case of non-linear grids. In the case of linear grids, nothing is changed, except for roundoff errors (this is reflected in the tweaks for some of the test cases).
> Axis: use spline interpolation for fallback grid/grid_node

- CHANGELOG.md
- postpic/datahandling.py
- test/test_datahandling.py
Changes:
* `postpic.Field.integrate` now has a new 'fast' method that uses numexpr, suitable for large datasets
> Field: added new integrate method 'fast'

- postpic/helper.py
Just added a hint towards the behaviour of kspace reconstruction in future epoch versions.
> kspace_epoch_like: add documentation regarding a future change in epoch

- postpic/io/npy.py
Since Axis objects store both grid and grid_node separately, they should also both be stored and loaded separately.
> io.npy: Fix _export_field_npy so that Axis.grid is also saved

- CHANGELOG.md
- postpic/datahandling.py
- postpic/helper.py
- test/test_datahandling.py
I'm working on a new implementation of the `Field.fft()` method that has 2 advantages over the current one:
1. Does not rely on slow, single threaded `fft.fftshift` and `fft.ifftshift` functions
2. Automatically removes linear phases that stem from having a grid, that does not have the 0-point exactly at the 0 index, like fft likes to have it. For both directions of the transformations
3. Handles both directions of the transform in a much more symmetric way
> Use improved handling of phases in fft

- postpic/io/npy.py
This is a follow-up to #207 to make `Field.loadfrom` again complatible with files saved before #207.
> _import_field_npy: adapted to load files w/o meta_ax_grids

- postpic/helper.py
Since the linear phase of the grid shift is now applied by the `fft()` method itself, it does not need to be applied by `_kspace_propagate_generator` in the case of a moving window. However, as `time_profile_at_plane` does not use `fft()` for the inverse transform, special handling is needed here.
> Fix bug #215

- postpic/__init__.py
workaround to fix #218
necessary if a zip is downloaded from github for a version without tag.
> use git sha as __version__ if nothing better is available

- postpic/datahandling.py
- postpic/helper.py
- test/test_helper.py
Small fix for `helper.jac_det` for the 1D-case. This fixes problems when using `pp.Field.map_coordinates` for 1D transforms.
> Fix helper.jac_det for 1d case

- postpic/particles/scalarproperties.py
this is numerically more stable for particles with `beta << 1`.
> paricles: update calculation of beta

- postpic/helper.py
Scipy intoduced another paramter for padding, which apparently was zero
before. Fixing this.
The scipy change is:
https://github.com/scipy/scipy/commit/9c299da04b9c419786a56c8e657aaabeb35f9069
Alex noted, that on his implementation, using the normal
`map_coordinates` function was really slow. (I am guessing due to extra
memory allocation), which is why he called the C-Function directly and
did all the checks within postpic. So keep it as is for really fast
coordinate mapping :)
Fix #261
> fixing map_coordinates

- .github/workflows/run-tests.yml
- postpic/datahandling.py
- postpic/datareader/dummy.py
- postpic/helper.py
- test/test_datahandling.py
* Scipy 1.14.0 removed deprecated scipy.integrate.trapz and scipy.integrate.simps functions
* numexpr introduced (in version 2.9?) sanity check rules, which result in invalid control character errors if ignored.
* numpy 2.0 changed __array_ufunc__ such that axis=None is possible.
* numpy 2.0 has removed np.asfarray
> compatibility to new numpy scipy and numexpr versions

- postpic/datareader/smileih5.py
The field of the laser envelope is real without imaginary part, therefore the structure of the hdf5 file is slightly different. With this small adjustment of getExpanded it is now possible to also process the real fields of Laser Envelope.
> smilei reader: add the possibility to process real fields
